use_frameworks!
platform :ios, '9.3'

target 'FALAtarashiiLib_Example' do
  pod 'FALAtarashiiLib', :path => '../'

  target 'FALAtarashiiLib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
